services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      MEMORY: "5120M"
      ONLINE_MODE: "false"
      USE_MEOWICE_FLAGS: "true"
      TZ: "America/Santiago"
      DIFFICULTY: "3"
      SIMULATION_DISTANCE: "14"
      VIEW_DISTANCE: "12"
      SPAWN_PROTECTION: "0"
      JVM_OPTS: "-Xms1G -Xmx5G"
      OPS: |
        soychriss
    volumes:
      - "./data:/data"
      - "./mods:/mods"
      # "init" container for mc to restore the data volume when empty
  restore-backup:
    # Same image as mc, but any base image with bash and tar will work
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - ./data:/data
      # Must be same mount as backups service, but can be read-only
      - ./mc-backups:/backups:ro
  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "24h"
      PRUNE_BACKUPS_DAYS: "1"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - ./data:/data:ro
      - ./mc-backups:/backups
